---
title: "Assingment-3"
output: html_document
date: "2024-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#partion of data
library(caret)
df <- read.csv('UniversalBank.csv')

set.seed(42)

# Split the data into training (60%) and validation (40%) sets
index <- createDataPartition(df$Personal.Loan, p = 0.6, list = FALSE)
train_data <- df[index, ]
val_data <- df[-index, ]

cat("Training set size:", nrow(train_data), "\n")
cat("Validation set size:", nrow(val_data), "\n")

```

```{r}
#A
 library(reshape2)

melted_data <- melt(train_data, id.vars = c("CCAvg", "Online", "Personal.Loan"))
pivot_table <- dcast(melted_data, CCAvg + Online ~ Personal.Loan, value.var = "value", fun.aggregate = length)

print(pivot_table)

```

```{r}
#B
count_loan_cc_online <- pivot_table[2, 4]  
count_cc_online <- pivot_table[2, 2] 
probability_loan_given_cc_online <- count_loan_cc_online / count_cc_online

print(probability_loan_given_cc_online)

```

```{r}
#c
library(reshape2)
melted_data <- melt(train_data, id.vars = c("Personal.Loan", "Online", "CCAvg"))

pivot_table_online <- dcast(melted_data, Online ~ Personal.Loan, value.var = "value", fun.aggregate = length)

pivot_table_cc <- dcast(melted_data, CCAvg ~ Personal.Loan, value.var = "value", fun.aggregate = length)

print("Pivot Table for Loan as a function of Online:")
print(pivot_table_online)

print("\nPivot Table for Loan as a function of CC:")
print(pivot_table_cc)

```

```{r}
# D.1
count_cc_loan_1 <- pivot_table[2, 2]  
count_loan_1 <- sum(pivot_table[, 2])  

probability_cc_given_loan_1 <- count_cc_loan_1 / count_loan_1

print(probability_cc_given_loan_1)

```

```{r}
#D.2
count_online_loan_1 <- pivot_table[2, 3]  
probability_online_given_loan_1 <- count_online_loan_1 / count_loan_1

print(probability_online_given_loan_1)

```

```{r}
#D.3
count_loan_1 <- sum(pivot_table[, 2]) 
total_samples <- sum(pivot_table)  
probability_loan_1 <- count_loan_1 / total_samples

# Display the result
print(probability_loan_1)

```

```{r}
#D.4
count_cc_loan_0 <- pivot_table[1, 2]  
count_loan_0 <- sum(pivot_table[, 1])  
probability_cc_given_loan_0 <- count_cc_loan_0 / count_loan_0

print(probability_cc_given_loan_0)

```

```{r}
#D.5
count_online_loan_0 <- pivot_table[1, 3]  
probability_online_given_loan_0 <- count_online_loan_0 / count_loan_0

print(probability_online_given_loan_0)

```

```{r}
#D.6
count_loan_0 <- sum(pivot_table[, 1])  
probability_loan_0 <- count_loan_0 / total_samples

print(probability_loan_0)

```

```{r}
#E
prob_cc_given_loan_1 <- probability_cc_given_loan_1
prob_online_given_loan_1 <- probability_online_given_loan_1
prob_loan_1 <- probability_loan_1

naive_bayes_prob <- prob_cc_given_loan_1 * prob_online_given_loan_1 * prob_loan_1

print(naive_bayes_prob)

```

```{r}
#F
prob_loan_1_given_cc_online <- pivot_table[2, 4] / sum(pivot_table[, 4])

print(prob_loan_1_given_cc_online)


```

```{r}
#G
library(e1071)
model <- naiveBayes(`Personal.Loan` ~ CCAvg + Online, data = train_data)

print("Naive Bayes Model Summary:")
print(model)

probabilities <- predict(model, train_data, type = "raw")
index_loan_1_cc_1_online_1 <- which(names(probabilities) == "1" & train_data$CC == 1 & train_data$Online == 1)
naive_bayes_prob_model <- probabilities[index_loan_1_cc_1_online_1]

print("Naive Bayes Probability from Model:")
print(naive_bayes_prob_model)

```
