---
title: "Assingment4"
output: html_document
date: "2024-03-14"
---

```{r}
library(readr)
Pharmaceuticals <- read_csv("~/Downloads/Pharmaceuticals.csv")

```

```{r}
#A
library(cluster)
numerical_data <- Pharmaceuticals[, 1:9]
numerical_data <- Pharmaceuticals[, sapply(Pharmaceuticals, is.numeric)]
scaled_data <- scale(numerical_data)
hc <- hclust(dist(scaled_data), method = "ward.D2")
plot(hc, hang = -1, cex = 0.6, main = "Dendrogram of Hierarchical Clustering")
num_clusters <- 4 
clusters <- cutree(hc, k = num_clusters)
Pharmaceuticals$Cluster <- clusters
cluster_summary <- aggregate(. ~ Cluster, data = Pharmaceuticals, FUN = mean)

print(cluster_summary)
print(Pharmaceuticals)

```

```{r}
#B
cluster_summary <- aggregate(. ~ Cluster, data = Pharmaceuticals, FUN = mean)
print(cluster_summary)
pattern_summary <- aggregate(. ~ Cluster, data = Pharmaceuticals, FUN = function(x) {
  levels(factor(x))[which.max(table(x))]
})
print(pattern_summary[c('Median_Recommendation', 'Location', 'Exchange')])

```
```{r}
#D
cluster_names <- c(
  "High Growth, High Profitability",
  "Moderate Growth, Moderate Profitability",
  "Low Growth, Low Profitability",
  "High Market Capitalization, Low Growth"
)
Pharmaceuticals$ClusterName <- cluster_names[clusters]

print(Pharmaceuticals[c('Cluster', 'ClusterName')])
```
```{r}
#C
pattern_analysis <- aggregate(cbind(Median_Recommendation, Location, Exchange) ~ Cluster, data = Pharmaceuticals, FUN = function(x) {
  c(Median = median(x), Mean = mean(x), SD = sd(x))
})
print(pattern_analysis)
```


```{r}

# Visualizations for variables 10 to 12 within each cluster
par(mfrow=c(1,3))  # Set up a 1x3 grid of plots
for (i in 10:12) {
  boxplot(get(names(Pharmaceuticals)[i]) ~ Pharmaceuticals$Cluster, data = Pharmaceuticals, main = names(Pharmaceuticals)[i])
}


```



